avg_train_accuracy: 0.346
avg_train_loss: 0.006
avg_type: avg_n_samples
dataset: emnist
epochs: 10
frac: 0.1
iid: 0
kernel_num: 9
kernel_sizes: 3,4,5
local_bs: 10
local_ep: 10
lr: 0.01
max_pool: 'True'
model: cnn
momentum: 0.5
norm: batch_norm
num_channels: 1
num_classes: 47
num_filters: 32
num_users: 100
optimizer: sgd
seed: 1
test_acc: 0.518
test_loss: 2.316
train_accuracy:
- 0.247
- 0.285
- 0.13
- 0.288
- 0.679
- 0.629
- 0.425
- 0.077
- 0.51
- 0.346
train_loss:
- 1.212
- 0.836
- 0.572
- 0.594
- 0.553
- 0.483
- 0.481
- 0.492
- 0.421
- 0.556
unequal: 1
verbose: 1
