avg_train_accuracy: 0.05
avg_train_loss: 0.004
avg_type: avg_n_samples
dataset: emnist
epochs: 10
frac: 0.1
iid: 0
kernel_num: 9
kernel_sizes: 3,4,5
local_bs: 10
local_ep: 10
lr: 0.01
max_pool: 'True'
model: cnn
momentum: 0.5
norm: batch_norm
num_channels: 1
num_classes: 47
num_filters: 32
num_users: 100
optimizer: sgd
seed: 1
test_acc: 0.511
test_loss: 2.364
train_accuracy:
- 0.0
- 0.15
- 0.091
- 0.391
- 0.088
- 0.492
- 0.825
- 0.624
- 0.605
- 0.05
train_loss:
- 1.126
- 0.813
- 0.713
- 0.667
- 0.66
- 0.459
- 0.449
- 0.525
- 0.461
- 0.421
unequal: 1
verbose: 1
