avg_train_accuracy: 0.312
avg_train_loss: 0.005
avg_type: avg_n_samples
dataset: emnist
epochs: 10
frac: 0.1
iid: 0
kernel_num: 9
kernel_sizes: 3,4,5
local_bs: 10
local_ep: 10
lr: 0.01
max_pool: 'True'
model: cnn
momentum: 0.5
norm: batch_norm
num_channels: 1
num_classes: 47
num_filters: 32
num_users: 100
optimizer: sgd
seed: 1
test_acc: 0.56
test_loss: 2.163
train_accuracy:
- 0.0
- 0.208
- 0.257
- 0.288
- 0.321
- 0.1
- 0.611
- 0.4
- 0.0
- 0.312
train_loss:
- 1.29
- 0.787
- 0.66
- 0.499
- 0.512
- 0.535
- 0.522
- 0.457
- 0.356
- 0.459
unequal: 1
verbose: 1
