avg_train_accuracy: 0.562
avg_train_loss: 0.005
avg_type: avg_n_samples
dataset: emnist
epochs: 10
frac: 0.1
iid: 0
kernel_num: 9
kernel_sizes: 3,4,5
local_bs: 10
local_ep: 10
lr: 0.01
max_pool: 'True'
model: cnn
momentum: 0.5
norm: batch_norm
num_channels: 1
num_classes: 47
num_filters: 32
num_users: 100
optimizer: sgd
seed: 1
test_acc: 0.535
test_loss: 2.163
train_accuracy:
- 0.009
- 0.139
- 0.0
- 0.721
- 0.319
- 0.462
- 0.142
- 0.975
- 0.9
- 0.562
train_loss:
- 1.228
- 0.862
- 0.625
- 0.572
- 0.46
- 0.525
- 0.542
- 0.521
- 0.424
- 0.526
unequal: 1
verbose: 1
